### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by redowl3** [Joelius300/ChartJSBlazor#94] opened 2019-09-26 15:19 UTC
I've probably missed a step somewhere but when I run using Blazor (server side) latest

I get 

: Blazor is not defined     at ChartJsInterop.js:5

when I check the console window.  Any ideas?

**Comment by TomaszGrzmilas** [comment] 2019-09-26 16:23
> I've probably missed a step somewhere but when I run using Blazor (server side) latest
> 
> I get
> 
> : Blazor is not defined at ChartJsInterop.js:5
> 
> when I check the console window. Any ideas?

Hi, could you give more details (some code) or link to github repo ?
Or steps to reproduce bug.

I just check and It work fine in my program.

BR

**Comment by Joelius300** [comment] 2019-09-26 17:02
This error will occur if you include the javascript from our library before including the javascript for blazor itself. For server-side this would mean that `_framework/blazor.server.js` was included after `_content/ChartJs.Blazor.Fork/ChartJsInterop.js`. If that's the case in your project, try including the `_framework`-stuff before anything else and report back to us if it worked. If it didn't, please show us the code in your `_Host.cshtml` (since you're running server-side); we can try fixing it from there.

You should always include the framework stuff first when working with blazor but if necessary we can mention that in the setup steps of the readme.

**Comment by redowl3** [comment] 2019-09-26 17:03
Thanks for the response - just tried that and works great.

**Comment by Joelius300** [comment] 2019-09-26 17:05
Awesome :)

I won't close this issue right now since this is a good reminder to put the disclaimer in the readme.

**Comment by SeppPenner** [comment] 2019-09-27 07:55
I have documented this under the known issues: https://github.com/Joelius300/ChartJSBlazor/wiki/Known-issues#uncaught-reference-error-blazor-is-not-defined-at-chartjsinteropjs5.

We should put this to the readme as well.

**Comment by SeppPenner** [comment] 2019-09-27 07:59
I put it to the getting started section as well: https://github.com/Joelius300/ChartJSBlazor/wiki/Getting-started.

Todo: Add this to the readme as well.

@Joelius300 do you think the way I described the issue is sufficient?

**Comment by Joelius300** [comment] 2019-09-27 08:14
### known issues

You need to add it for client-side as well. The error should occur there too but I think it's a different js you need to include. You can test that with a client-side application and you will also be able to see what js-file is included for blazor in `index.html`. Then you can mention that in the wiki.

Also, I see that you also used 'try to..'. I only said that because I wasn't 100% sure if that was the issue they were experiencing. In this case we're describing this exact issue and we exactly know how to fix it so you should write something like 'to fix it you have to..'.

### getting started

It shouldn't be its own Step. Just call it 'disclaimer' or so under step 4 instead of making it step 5.

**Comment by SeppPenner** [comment] 2019-09-27 11:58
I will work on all this documentation things today in the evening (I have more time then).

**Comment by SeppPenner** [comment] 2019-09-30 09:05
Known issues:

- [x] Add info for the client-side as well.
- [x] Remove 'try to'

Getting started:

- [x] Made step 5 `Disclaimer` under step 4

I will update the readme and afterwards this issue can be closed as well @Joelius300: https://github.com/Joelius300/ChartJSBlazor/pull/98

**Closed as completed** 2019-10-04 17:52 UTC
Labels: bug, documentation
